### ISSUE TITLE
Empty result when making a search from a search result

### ISSUE THREAD

**Issue by jordyamc** [FengMoeTeam/NHentai-android#59] opened 2016-10-30 05:35 UTC
When doing a search from a search result the screen show any result

**Comment by kaoru0429** [comment] 2016-11-09 15:28
You've back to the Homepage，then do the 2nd search

**Comment by jordyamc** [comment] 2016-11-10 02:12
i know, but i think the point of putting a search bar in the search result is to make another search from there

**Comment by NotCR** [comment] 2016-11-13 09:25
Hello guys, sorry for the silence i have a ton of work. I cant reproduce this issue myself, im searching something and inside the result page  im searching again, but for me its giving me the proper result of the new query to search. Am i missing something to reproduce it?

**Comment by NotCR** [comment] 2016-11-14 02:18
guys should be fixed in the new release, can you guys check

**Comment by jordyamc** [comment] 2016-11-14 14:44
@NotCR yes. is solved :)

**Closed** 2017-01-30 03:35 UTC
